config/routes.rb
CityStories::Application.routes.draw do
  root 'pages#home'
  match '/spur',       to: 'pages#spur',         via: 'get'
  match '/blog',       to: 'pages#blog',         via: 'get'
  match '/partners',   to: 'pages#partners',     via: 'get'
  match '/about',      to: 'pages#about',        via: 'get'

  match '/team',       to: 'pages#team',         via: 'get'
  match '/schedule',   to: 'pages#schedule',     via: 'get'
  match '/films',      to: 'pages#films',        via: 'get'
  match '/resources',      to: 'pages#resources',        via: 'get'
  match '/tickets',      to: 'pages#tickets',        via: 'get'
  match '/contact',      to: 'pages#contact',        via: 'get'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def spur
  end

  def blog
  end

  def partners
  end

  def about
  end

  def team
  end

  def schedule
  end

  def films
  end

  def resources
  end

  def tickets
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SF Urban Film Fest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<link rel="shortcut icon" href="http://images/fav.ico" />
<meta property="og:image" content="http://www.sfurbanfilmfest.com/assets/fp-c95c0d4d454f170df534b73f6211a74d.jpg"/>
</head>

<body>

<div class="navbar navbar-wrapper drop">
	<div id="cssmenu">
   
 
  <div class="navbar-inner">
    
      <nav class="">
      
      
        <div class="container extratop2">
          <ul class="navbar-brand">
		     <a href="/" class=""> 
               <span class="ab", data-title="SF Urban Film Fest"> <%= image_tag("logo.jpg", alt: "cv")%></span>
            </a>  
        </div>
<div class="navbar-brand">
      <div id="reveal">
            <a href="" class="" id="nav-text">
      <span data-title="Team">   </span>
      </a>

			<a href="/" class="roll" id="nav-text">
			<span data-title="Home">Home</span>
			</a>
			<a href="/about" class="roll" id="nav-text">
			<span data-title="About">About</span>
			</a>
      
            
			<a href="/team" class="roll" id="nav-text">
			<span data-title="Team">Team</span>
			</a>
			<a href="/schedule" class="roll" id="nav-text">
			<span data-title="Schedule">Schedule</span>
			</a>
      <a href="/films" class="roll" id="nav-text">
      <span data-title="Films">Films</span>
      </a>
      <a href="/tickets" class="roll" id="nav-text">
      <span data-title="Tickets">Tickets</span>
      </a>
      <a href="/blog" class="roll" id="nav-text">
      <span data-title="Blog">Blog</span>
      </a>
      <a href="/resources" class="roll" id="nav-text">
      <span data-title="Resources">Resources</span>
      </a>
      <a href="/contact" class="roll" id="nav-text">
      <span data-title="Contact">Contact</span>
      </a>
        </ul>
      </nav>
   </div>
   </div> 
 </div>
  </div>
</div>

<%= yield %>
<div class="container">
<footer class="footer">
  <small>
    <p>developed and designed by <a href="http://www.alexzimmer.com">Alex Zimmer</a></p>
    
  </small>
  <nav>
    <ul>
      <li><%= image_tag("logo.jpg", alt: "cv")%></li>
 <li><a href="https://www.facebook.com/events/1499269766982179/"> <%= image_tag("fbsmall.jpg", alt: "fb")%> </a> </li>
 <li><a href="http://twitter.com/sfurbanfilmfest"> <%= image_tag("twittersmall.jpg", alt: "twit")%> </a> </li>
      <li><%= link_to "Partners",   partners_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Volunteer", contact_path %></li>

    </ul>
  </nav>
</footer>
</div>
</body>
</html>

app/views/layouts/header.html.erb
<div class="navbar navbar-wrapper">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "urban planning {City Stories} film festival", root_path, id: "logo" %>
       </div>
      <div id="reveal">
      <nav>
        <ul class="nav navbar-nav pull-right">
			
			<a href="/" class="roll" id="nav-text">
			<span data-title="Home">Home</span>
			</a>
			<a href="/about" class="roll" id="nav-text">
			<span data-title="About">About</span>
			</a>
			<a href="/team" class="roll" id="nav-text">
			<span data-title="Team">Team</span>
			</a>
			<a href="/schedule" class="roll" id="nav-text">
			<span data-title="Schedule">Schedule</span>
			</a>
        </ul>
      </nav>
   
   </div>
  </div>
</div>

app/views/layouts/shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/pages/about.html.erb
        <div class="hero-unit extratop3 msides2">
<p style="font-weight: bold;">Fest of the Film Fest</p>
<p style="font-size:small;font-weight: bold;">Friday, November 7 </p>
<p style="font-size:small;font-weight: bold;">SPUR Gallery’s "Infinite Loop" Lounge and Theatre </p>
<p style="font-size:small" style="font-weight: bold;">Tickets: $25  (Limited to 100)</p>

<p style="font-size:small">Doors open 6:30pm.  Enjoy the "Infinite Loop" short films mash-up. </p>  

<p style="font-size:small">Complimentary cocktails and served by local urban planners turned mixers and shakers.  </p>

<p style="font-size:small">@7:30pm, <i><b>Impossible Light</i></b> documentary screening/Q&A the makers, Jeremy Ambers and Ben Davis, a Co-Presentation with the Bay Area Video Coalition </p>
<p style="font-size:small">Keep the party going in the Infinite Loop Lounge until 11pm, alternate between the sounds of DJ and “Silent Frisco” headphones for Infinite Loop audio to follow closely urban history through the lens of planners and filmmakers.
        </p>    
</div>

<div class="hero-unit msides2">
        
        <p style="font-weight: bold;">Urban Planning as a Design Problem </p>
<p style="font-size:small;font-weight: bold;">Saturday, November 8 </p>
<p style="font-size:small;font-weight: bold;">All Day Ticket: $22 (Limited to 100) </p>

<p style="font-size:small" >The design of a city influences our every day experience, it’s economic health, and how a sense of community can be fostered.  The films featured on Saturday portray urban planning as a design problem and include the mesmerizing <i><b>Urbanized</i></b>, the inspiring <i><b>Rock the Boat</i></b>, and a fascinating segment from the locally produced work-in-progress <i><b>Saving the City</i></b>.  The day will end with a panel discussion on the evolution of San Francisco’s in-town new town, Mission Bay, a neighborhood designed from scratch.  As part of the panel, Ron Blatman, producer and director of <i><b>Saving the City</i></b> will discuss how he chose Mission Bay as the focus of the San Francisco segment in this upcoming PBS TV series. 
        </p>
        
</div>

<div class="hero-unit msides2">
        
        <p style="font-weight: bold;">Urban Planning as a Search for Social Equity </p>
<p style="font-size:small;font-weight: bold;">Sunday, November 9 </p>
<p style="font-size:small;font-weight: bold;">All Day Ticket: $18 (Limited to 100) </p>

<p style="font-size:small">We all seek to be heard and appreciated.  Urban planning, when viewed through the lens as a search for social equity, recognizes the contributions of all segments of the population in making our cities vibrant and resilient.  In this light, urban planning is a complex system of individual rights, public policies, private markets, and cultural values which often times conflict but as often, converge.  The films on Sunday illuminate the struggle for social equity as cities carry out housing, economic development and transportation strategies with the intent of improving the lives of all but with controversial results.  <b><i>The Pruitt-Igoe Myth</b></i> deconstructs the myth perpetuated by the image seared into our collective unconscious of a public housing project imploding.  <b><i>The Fillmore</b></i> tells the story of a beloved neighborhood in San Francisco rocked by World War II and mid-century Federal urban policy.  <i><b>5 Blocks</i></b> is a work in progress showing the changes happening in real time in downtown San Francisco’s Central Market Street area. 
        </p>

        <p style="font-size:small">Join the filmmakers of <i><b>The Fillmore</i></b>, Peter L. Stein, <i><b>5 Blocks</i></b>, Robert Cortlandt and Dan Goldes, and the author of “Cool Gray City of Love: 49 Views of San Francisco” and Executive Editor of <i>San Francisco magazine</i>, Gary Kamiya, as they discuss how each of them approached their stories of neighborhood change. Amy Cohen of the Mayor’s Office of Economic and Workforce Development will shed light on how storytelling has become an integral part of creating a unifying economic development policy for the City.</p>
        
</div><div class="hero-unit msides2">
<p style="font-weight: bold;">Infinite Loop/Reverse “Silent Frisco” </p> 
<p style="font-size:small;font-weight: bold;">Friday, Saturday, Sunday November 7-9</p>
<p style="font-size:small;font-weight: bold;">SPUR Gallery’s "Infinite Loop" Lounge</p>

<p style="font-size:small">The SF Urban Film Fest "Infinite Loop" is a mash-up of urban planning short videos circa 1930’s to the present.  The visual experience is enhanced with “Silent Frisco” headphones from SF’s own Sunset Promotions.  
</p>
</div>

<div class="hero-unit msides2">
        
        <p style="font-weight: bold;">INSPIRE - ENGAGE - CELEBRATE </p>
<p style="font-size:small;font-weight: bold;">Saturday and Sunday November 8 & 9 </p>
<p style="font-size:small;font-weight: bold;">SPUR Gallery's "Infinite Loop" Lounge </p>

<p style="font-size:small"> Engage with local membership organizations working to improve your city.  Visit their tables, watch locally produced innovative video campaigns and learn how you can get involved. Come celebrate our urban community. </p>

<p style="font-size:small;font-weight: bold;">Saturday, November 8</p>
<p style="font-size:small;font-weight: bold;">- The San Francisco Bicycle Coalition </p>
<p style="font-size:small;font-weight: bold;">- San Francisco Public Utilities Commission (SFPUC)</p>

<p style="font-size:small;font-weight: bold;">Sunday, November 9</p>
<p style="font-size:small;font-weight: bold;">- Walk SF </p>
<p style="font-size:small;font-weight: bold;">- Bay Area Video Coalition (BAVC) </p>

</div>
        



        

</div>
<div class="">

 <hr style="height:1px;border:none;color:#333;background-color:#333;" />

app/views/pages/blog.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_EN/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="hero unit msides extratop3">
<p style="font-weight: bold;">Was the first urban planner a photographer? </p>

<p> Although the SF Urban Film Fest maybe the first urban planning film festival, images have always inspired urban planning.  The heart-wrenching photography of Jacob Riis in his seminal book “How The Other Half Lives” chronicled the lives of poor immigrants in the tenements of New York City’s Lower East Side in the early 20th century.  His photographs inspired the Tenement Housing Movement who in turn pushed New York City to enact the nation’s first laws regulating housing conditions.  Visual activism is often over shadowed by discussions of the physical environment, grass-roots organizing, and legislative change in lessons of urban history.  At the SF Urban Film Fest, we bring visual storytelling to the forefront in the creation of our urban future. </p>

</div>



<hr class="msides" style="height:1px;border:none;color:#333;background-color:#333;" />

<div class="hero unit msides extratop2">
<p style="font-weight: bold;">What is an urban planning film festival? </p>

<p> At the SF Urban Film Fest, we screen films showing how the built environment effects society - and vice versa - in cities.  These urban planning films highlight the hard work and commitment of visionary leaders, regular citizens, and government forging change in cities.  The emerging urban planning film genre shares common ground with documentaries from the environmental and global social justice movements.  The most notable of these films is the Academy Award winning An Inconvenient Truth (2006, USA) which utilized the star power of former U.S. Vice President Al Gore and transformed an ivory tower scientific debate into a global popular discourse about climate change.</p>

<p>What differentiates the SF Urban Film Fest from other film festivals is our focus on connecting the themes of the films to campaigns actively being pursued by governmental and non-profit organizations working for change in San Francisco.  We want to prove that a good film can inspire you to join others in making San Francisco a better place to live. </p>

</div>


<hr class="msides" style="height:1px;border:none;color:#333;background-color:#333;" />

<div class="hero unit msides extratop2">
<p style="font-weight: bold;"> SF the hot bed of urban planning filmmaking? </p>

<p> Who knew San Francisco is a hotbed of urban planning inspired filmmaking? The SF Urban Film Fest will feature three days of locally produced documentaries and works-in-progress including Q&A with the filmmakers, Jeremy Ambers of Impossible Light, Ron Blatman of Saving the City, and Dan Goldes and Robert Cortland of 5 Blocks.  Each filmmaker approaches the topic of city-making differently, lyrically like Impossible Light, in contrasts as in Saving the City, and from the ground up as in 5 Blocks.  San Francisco is also the home of the Bay Area Video Coalition (BAVC), a non-profit turning on residents of all ages to storytelling and video production. Learn about BAVC at their booth on Sunday.</p>

</div>


<hr class="msides" style="height:1px;border:none;color:#333;background-color:#333;" />

<div class="hero unit msides extratop2">

<p style="font-weight: bold;">SF Urban Asks Urban Planner/Artist James Rojas: “How do you sustain public engagement in the urban planning process?” </p>

<p style="font-weight: bold;">James: </p>
	<p> “Creativity.  Urban planners need to capture the emotional and experiential aspects of city life in their methods and tools.  Currently, the outreach tools - lists, dots on a map, stakeholder groups - are too abstract.  The creative process on the other hand is one of passion, discovery, and self-satisfaction.  Artists, filmmakers, and writers are driven by the creative process which allows them to imagine, investigate, construct, and reflect. </p>

<p style="font-weight: bold;">SF Urban: </p>
	<p> How does your idea about creativity translate to public participation in urban planning?</p>
 
<p style="font-weight: bold;">James: </p>
	<p> The participant becomes the artist, writer, or filmmaker.  Let the public create narratives about how they experience urban life.  Let them tell stories, visualize their ideal environments, document how they experience the physical world, share their ideas with others, and ultimately have their ideas validated.</p>
 
<p style="font-weight: bold;">SF Urban: </p>
	<p> That kind of work has no end. 
 
<p style="font-weight: bold;">James: </p>
	<p> Exactly. The city is an artist that is always producing new work to solve problems and desires.  </p>

</div>

<div class="fb-comments hero unit msides extratop2" data-href="http://www.sfurbanfilmfest.com/blog" data-width="600" data-numposts="
5" data-colorscheme="light"></div>

app/views/pages/contact.html.erb
<div class="container-fluid hero-unit extratop3">
	<p style="font-weight: bold; font-size:small">Contact Us</p>
<p style="font-size:small">
	<div class="row-fluid">
		<div class="span2">
		</div>
    <div class="span3">
<a href="https://www.facebook.com/events/1499269766982179/"> <%= image_tag("facebook.jpg", alt: "fb")%> </a>
	</div>
 <div class="span3">
 	<a style="font-size:small" href="mailto:sfurbanfilmfest@gmail.com"><b><%= image_tag("gmail.jpg", alt: "gm")%></b>
 	</a>
    	</div>
    <div class="span3">
		<a href="http://twitter.com/sfurbanfilmfest"> <%= image_tag("twitter.jpg", alt: "twit")%> </a>
	</div>
</div>


</div>
<div class="ab"><iframe src="https://docs.google.com/forms/d/1G9lCrgiL1GWXIMeX_gIiEU_FyHxcqJwkPB9f9vkuIzM/viewform?embedded=true" width="760" height="620" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
</p>
</div>

app/views/pages/films.html.erb
<div class="hero unit msides extratop3">
<p style="font-weight: bold;">Films (in alphabetical order)</p> 

<hr class="msides" style="height:1px;border:none;color:#333;background-color:#333;" />


<p style="font-weight: bold;"><i>Every Speed  (2013, 7 minutes)</i></p>
<p style="font-weight: bold;">Director: Julia Fuller </p>

<a href="http://www.everyspeedfilm.com"><p><i>www.everyspeedfilm.com</p></i></a>

An atmospheric and experiential exploration of able and disabled bodies moving through urban spaces and negotiating transport options. 

</div>
<hr class="msides" style="height:1px;border:none;color:#333;background-color:#333;" />

<div class="hero unit msides extratop2">

<p style="font-weight: bold;"><i>5 Blocks (work in progress, 8 minutes) </i></p>
<p style="font-weight: bold;">Directors: Robert Cortlandt and Dan Goldes </p>

<a href="http://www.5blocksproject.com"><p><i>www.5blocksproject.com</p></i></a>

A work-in-progress tracking the radical changes in the five block area of Mid-Market, San Fran-cisco since prior to the recent tech-boom to the present. 

</div>
<hr class="msides" style="height:1px;border:none;color:#333;background-color:#333;" />

<div class="hero unit msides extratop2">

<p style="font-weight: bold;"><i>Impossible Light  (2013, 70 minutes) </i></p>
<p style="font-weight: bold;">Director: Jeremy Ambers </p>

<iframe width="560" height="315" src="//www.youtube.com/embed/pPGNVwHuaU8" frameborder="0" allowfullscreen></iframe>

<p>A full-length documentary about the San Francisco Bay Bridge “Bay Lights” sculpture which was realized in an impossible timeframe of two years. </p>

</div>
<hr class="msides" style="height:1px;border:none;color:#333;background-color:#333;" />


<div class="hero unit msides extratop2">

<p style="font-weight: bold;"><i>Neighborhoods: The Hidden Cities of San Francisco: The Fillmore (1999, 84 minutes)</i></p>
<p style="font-weight: bold;">Director: Peter L. Stein </p>

<a href="http://www.peterlstein.com/tv--film.html#Fillmore"><p><i>http://www.peterlstein.com</p></i></a>

Part of a PBS series on neighborhoods, this segment tells the story of San Francisco’s premier Japanese-American and African-American community and the profound impact urban renewal had on the fabric of American cities, including that of the Fillmore in San Francisco. 

</div>

<hr class="msides" style="height:1px;border:none;color:#333;background-color:#333;" />
<div class="hero unit msides extratop2">

<p style="font-weight: bold;"><i>Plan of the City  (2011, 15 minutes)</i></p>
<p style="font-weight: bold;">Director: Joshua Frankel </p>

A classical ensemble blasts around in an urban universe to upbeat tunes. Perhaps the first ur-ban planning music video. 

</div>
<hr class="msides" style="height:1px;border:none;color:#333;background-color:#333;" />

<div class="hero unit msides extratop2">

<p style="font-weight: bold;"><i>Rock the Boat  (2011, 54 minutes) </i></p>
<p style="font-weight: bold;">Director: Thea Mercouffer </p>

<iframe width="560" height="315" src="//www.youtube.com/embed/MqJKQnMhT28" frameborder="0" allowfullscreen></iframe>

<p>A full-length documentary about citizens reclaiming the LA River and winning over the U.S. Army Corps of Engineers to reverse its own work and return the waterway to its original state. </p>

</div>

<hr class="msides" style="height:1px;border:none;color:#333;background-color:#333;" />

<div class="hero unit msides extratop2">
 
<p style="font-weight: bold;"><i>The Pruitt - Igoe Myth  (2012, 79 minutes) </i></p>
<p style="font-weight: bold;">Director: Chad Freidrichs </p>

<iframe width="560" height="315" src="//www.youtube.com/embed/g7RwwkNzF68" frameborder="0" allowfullscreen></iframe>

<p>A full-length documentary about the people who created a community in an inhospitable public housing project in St. Louis, MO. </p>

</div>
<hr class="msides" style="height:1px;border:none;color:#333;background-color:#333;" />

<div class="hero unit msides extratop2">

<p style="font-weight: bold;"><i>Saving The City  (work-in-progress, 20 minutes) </i></p>
<p style="font-weight: bold;">Director: Ron Blatman </p>

<iframe src="//player.vimeo.com/video/86565736" width="560" height="315" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

<a href="http://www.savingthecity.org"><p><i>www.savingthecity.org  </p></i></a>

A work-in-progress which includes a segment comparing two neighborhoods designed from scratch - Mission Bay in San Francisco and a similar neighborhood in Vancouver, Canada.

</div>
<hr class="msides" style="height:1px;border:none;color:#333;background-color:#333;" />

<div class="hero unit msides extratop2">

<p style="font-weight: bold;"><i>Urbanized </i></p>
<p style="font-weight: bold;">Director: Gary Hustwit (2011, 85 minutes) </p>

<iframe width="560" height="315" src="//www.youtube.com/embed/6jpN8kI0-pY" frameborder="0" allowfullscreen></iframe>

<p>A full length documentary about the innovative responses to rapid urbanization by the cities of Bogota in Columbia, Santiago in Chile, Cape Town in South Africa, and Stuttgart, Germany.</p>

</div>
<hr class="msides" style="height:1px;border:none;color:#333;background-color:#333;" />

<div class="hero unit msides extratop2">

<p style="font-weight: bold;"><i>Walk At Her Own Risk (10 minutes commissioned by Walk SF)</i> </p>
<p style="font-weight: bold;">Director: Dolly Totes </p>

A story of a young woman reconstructing her life after a recent pedestrian collision in San Francisco. 

</div>

app/views/pages/home.html.erb
<div class="extratop4">
</div>

<div id="myCarousel" class="carousel fade"> 
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner">
        <div class="item active">
            <a href=""> 
                <%= image_tag("fp.jpg", alt: "0")%>
            </a>
        </div>
        <div class="item">
            <a href=""> 
                <%= image_tag("fp22.jpg", alt: "1")%>
            </a>
        </div>
        <div class="item">
            <a href=""> 
                <%= image_tag("fp33.jpg", alt: "2")%>
            </a>
        </div>
        <div class="item">
            <a href=""> 
                <%= image_tag("fp44.jpg", alt: "3")%>
            </a>
        </div>
    </div>

    </div>
<script>
$(document).ready(function() {
  $('.carousel').carousel();
  $('.carousel').on('slid', function() {
    var to_slide = $('.carousel-inner .item.active').attr('id');
    $('.carousel-indicators').children().removeClass('active');
    $('.carousel-indicators [data-slide-to=' + to_slide + ']').addClass('active');
  });
});
</script>

<div class ="hero-unit msides">
    <p style="font-weight: bold;font-size:large"> November 6th - 9th, 2014
    <style="font-weight: bold;font-size:large;" class="pull-right"> SPUR</p>
</div>

<div class ="hero-unit extratop2 msides2">
    <p style="font-size:small"> Welcome to the <b>SF Urban Film Fest</b> – a film festival focused on <b>URBAN PLANNING</b>, <b>CIVIC ENGAGEMENT</b>, and <b>FILM</b>. </p>
 
<p style="font-size:small">The goals of the SF Urban Film Fest are to educate the general public on urban planning approaches to urban design problems and questions of social equity and to inspire civic engagement through the most dynamic of visual media, film and video. </p>
<p style="font-size:small"> Come join us for four days of film, filmmaker/urban planner panels, and a Friday night party celebrating our hopes and dreams for dynamic cities, including our own, San Francisco.</p>
</div>

<div class="row-fluid msides3">
    <div class="span1">
</div>
    <div class="span5">
<div class="hero-unit">
		
		<p style="font-size:small">SF Urban Film Fest will take place from <b>November 6th to 9th at SPUR</b>, San Francisco Planning and Urban Research, located at <b>654 Mission St, San Francisco.</b>
        </p>
      
		
</div>
</div>

	<div class="span5">
	<div class="hero-unit">
		<p style="font-size:small">	
		<a href="/tickets">Tickets</a> will be <b>$22 for a day pass on Saturday, $18 on Sunday</b>, and <b>$25 </b> for the Friday night kickoff party and screening, <b> The Fest at the Film Fest </b>.
        </p>
		</div>
    </div>
    <div class="span1">
</div>
</div>
<hr style="height:1px;border:none;color:#333;background-color:#333;" />

    <div class ="hero-unit extratop2 msides">
<p style="font-size:small"><i>The SF Urban Film Fest is rooted in the belief that good films can inspire civic engagement.  We show films about painful urban histories, visionary planning, and passionate citizens making a difference for their street, neighborhood, or city.</i> </p>

<p style="font-size:small"><i>These urban planning stories have inspired the documentary filmmakers whose work we show this weekend.  We hope these stories will inspire you too because urban planning needs you.</i></p>

<p style="font-size:small"><i>The stories abound daily of the many crises San Francisco faces - housing, transportation, open space, public education, sea-level rise, natural disasters, and income inequality to name a few.  It will take all of us, not just urban planners, to tackle these problems.  We hope SF Urban Film Fest will ignite our collective imagination and resolve to create a resilient, just and heart-stoppingly beautiful city. </i></p>
<p style="font-size:small"><i>Fay Darmawi,</i>
</p>
<p style="font-size:small">
<i>Founder and Executive Producer </i>
</p>
</div>
<div class ="hero-unit extratop2 msides2">
<p style="font-size:small">We want to thank Charles Long and Lydia Tan for underwriting the event and believing in us. We also want to acknowledge SPUR as our generous host.</p>
</div>

    <hr style="height:1px;border:none;color:#333;background-color:#333;" />
    <div class="hero-unit msides2">
<p style="font-weight: bold; font-size:small"> Our Partners </p>
</div>
    <div class="row msides3">


        <div class="span3">
            <div class="hero-unit">
                <%= image_tag("spur.jpg", alt: "spur")%>
            </div>
        </div>

        <div class="span3">
            <div class="hero-unit">
                <%= image_tag("sfbike.jpg", alt: "bike")%>
            </div>

        </div>
  
        <div class="span3">
            <div class="hero-unit">
                <%= image_tag("sfpuc.jpg", alt: "sfpuc")%>
            </div>
        </div>
     
        <div class="span3">
            <div class="hero-unit">
                <%= image_tag("walksf.jpg", alt: "walksf")%>
            </div>
        </div>

          <div class="span3">
            <div class="hero-unit">
                <%= image_tag("bavc.jpg", alt: "bavc")%>
            </div>
        </div>

    </div>
</div>
</div>

app/views/pages/spur.html.erb
<p>SPUR!</p>